'use client';
import { useEffect, useRef, useState } from 'react'; import { Circle, Layer, Rect, Stage, Text, Transformer } from 'react-konva'; import type Konva from 'konva'; import type { CanvasElement } from '../types/canvas';
type Props = { elements: CanvasElement[]; selectedId: string | null; width: number; height: number; onSelect: (id: string | null) => void; onChange: (id: string, patch: Partial<CanvasElement>) => void; stageRef: React.RefObject<Konva.Stage | null> };
const minimum = 12;
export default function CanvasStage({ elements, selectedId, width, height, onSelect, onChange, stageRef }: Props) {
 const transformer = useRef<Konva.Transformer>(null); const nodes = useRef<Record<string, Konva.Node | null>>({}); const [scale, setScale] = useState(1);
 useEffect(() => { const update = () => setScale(Math.min(1, Math.max(.45, (window.innerWidth - 390) / width))); update(); window.addEventListener('resize', update); return () => window.removeEventListener('resize', update); }, [width]);
 useEffect(() => { const node = selectedId ? nodes.current[selectedId] : null; if (transformer.current) { transformer.current.nodes(node ? [node] : []); transformer.current.getLayer()?.batchDraw(); } }, [selectedId, elements]);
 const transformed = (element: CanvasElement, node: Konva.Node) => { const sx = node.scaleX(); const sy = node.scaleY(); const base = { x: node.x(), y: node.y(), rotation: ((node.rotation() % 360) + 360) % 360 }; if (element.type === 'circle') { const radius = Math.max(minimum / 2, (element.radius || 1) * Math.max(Math.abs(sx), Math.abs(sy))); onChange(element.id, { ...base, radius }); } else { onChange(element.id, { ...base, width: Math.max(minimum, (element.width || 1) * Math.abs(sx)), height: Math.max(minimum, (element.height || 1) * Math.abs(sy)) }); } node.scaleX(1); node.scaleY(1); };
 return <div className="stage-viewport"><div className="stage-wrap" style={{ width: width * scale, height: height * scale }}><Stage ref={stageRef} width={width} height={height} scaleX={scale} scaleY={scale} className="stage" onMouseDown={(e) => { if (e.target === e.target.getStage()) onSelect(null); }}>
  <Layer>{elements.map((element) => { const shared = { id: element.id, ref: (node: Konva.Node | null) => { nodes.current[element.id] = node; }, x: element.x, y: element.y, rotation: element.rotation, fill: element.fill, draggable: true, onClick: () => onSelect(element.id), onTap: () => onSelect(element.id), onDragEnd: (e: Konva.KonvaEventObject<DragEvent>) => onChange(element.id, { x: e.target.x(), y: e.target.y() }), onTransformEnd: (e: Konva.KonvaEventObject<Event>) => transformed(element, e.target) };
   if (element.type === 'rectangle') return <Rect key={element.id} {...shared} width={element.width} height={element.height} cornerRadius={4} />;
   if (element.type === 'circle') return <Circle key={element.id} {...shared} radius={element.radius} />;
   return <Text key={element.id} {...shared} width={element.width} height={element.height} text={element.text} fontSize={element.fontSize} fontFamily="Inter, Arial, sans-serif" verticalAlign="middle" />;
  })}<Transformer ref={transformer} rotateEnabled enabledAnchors={['top-left','top-center','top-right','middle-left','middle-right','bottom-left','bottom-center','bottom-right']} boundBoxFunc={(oldBox, newBox) => (Math.abs(newBox.width) < minimum || Math.abs(newBox.height) < minimum ? oldBox : newBox)} /></Layer>
 </Stage></div></div>;
}
