'use client';
import { useCallback, useMemo, useRef, useState } from 'react'; import type Konva from 'konva'; import { useCanvasEditor } from '../hooks/useCanvasEditor'; import type { CanvasElement } from '../types/canvas'; import { canvasApi } from '../services/canvasApi'; import CanvasStage from './CanvasStage'; import PropertiesPanel from './PropertiesPanel'; import SavedCanvases from './SavedCanvases';
const CANVAS_WIDTH = 900, CANVAS_HEIGHT = 600;
const makeElement = (type: CanvasElement['type']): CanvasElement => { const id = crypto.randomUUID(); const center = { x: 375, y: 250 }; if (type === 'rectangle') return { id, type, ...center, width: 150, height: 100, rotation: 0, fill: '#635bff' }; if (type === 'circle') return { id, type, x: 450, y: 300, radius: 60, rotation: 0, fill: '#f16b4a' }; return { id, type, ...center, width: 220, height: 58, rotation: 0, fill: '#1d2433', text: 'Double click to edit', fontSize: 23 }; };
export default function Editor() {
 const editor = useCanvasEditor(); const [name, setName] = useState('Untitled design'); const [currentId, setCurrentId] = useState<string | null>(null); const [library, setLibrary] = useState(false); const [canvases, setCanvases] = useState<Array<any>>([]); const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState<{ text: string; error?: boolean } | null>(null); const stageRef = useRef<Konva.Stage | null>(null); const savedSignature = useRef(JSON.stringify({ name: 'Untitled design', elements: [] }));
 const signature = useCallback(() => JSON.stringify({ name, elements: editor.elements }), [name, editor.elements]); const dirty = savedSignature.current !== signature(); const selected = useMemo(() => editor.elements.find((item) => item.id === editor.selectedId), [editor.elements, editor.selectedId]); const toast = (text: string, error = false) => { setNotice({ text, error }); window.setTimeout(() => setNotice(null), 3500); };
 const save = async () => { if (!name.trim()) return toast('Give this canvas a name before saving.', true); setSaving(true); try { const payload = { name: name.trim(), width: CANVAS_WIDTH, height: CANVAS_HEIGHT, elements: editor.elements }; const result = currentId ? await canvasApi.update(currentId, payload) : await canvasApi.create(payload); setCurrentId(result._id); setName(result.name); savedSignature.current = JSON.stringify({ name: result.name, elements: result.elements }); toast(currentId ? 'Canvas updated.' : 'Canvas saved to your library.'); } catch (error) { toast(error instanceof Error ? error.message : 'Could not save canvas.', true); } finally { setSaving(false); } };
 const openLibrary = async () => { setLibrary(true); setLoading(true); try { setCanvases(await canvasApi.list()); } catch (error) { toast(error instanceof Error ? error.message : 'Could not load canvases.', true); } finally { setLoading(false); } };
 const load = async (id: string) => { setLoading(true); try { const canvas = await canvasApi.get(id); editor.replace(canvas.elements); setName(canvas.name); setCurrentId(canvas._id); savedSignature.current = JSON.stringify({ name: canvas.name, elements: canvas.elements }); setLibrary(false); toast('Canvas loaded.'); } catch (error) { toast(error instanceof Error ? error.message : 'Could not load canvas.', true); } finally { setLoading(false); } };
 const removeSaved = async (id: string) => { const item = canvases.find((canvas) => canvas._id === id); if (!window.confirm(`Delete “${item?.name || 'this canvas'}”? This cannot be undone.`)) return; try { await canvasApi.remove(id); setCanvases((items) => items.filter((item) => item._id !== id)); if (currentId === id) { setCurrentId(null); setName('Untitled design'); editor.replace([]); savedSignature.current = JSON.stringify({ name: 'Untitled design', elements: [] }); } toast('Saved canvas deleted.'); } catch (error) { toast(error instanceof Error ? error.message : 'Could not delete canvas.', true); } };
 const fresh = () => { if (dirty && !window.confirm('Discard unsaved changes and create a new canvas?')) return; editor.replace([]); setCurrentId(null); setName('Untitled design'); savedSignature.current = JSON.stringify({ name: 'Untitled design', elements: [] }); };
 const exportPng = () => { if (!stageRef.current) return; const selectedId = editor.selectedId; editor.setSelectedId(null); requestAnimationFrame(() => { const url = stageRef.current?.toDataURL({ pixelRatio: 2 }); if (url) { const link = document.createElement('a'); link.download = `${name.trim() || 'canvas'}.png`; link.href = url; link.click(); } editor.setSelectedId(selectedId); }); };
 return <main className="app-shell"><header className="topbar"><div className="brand"><b>Studio</b><span>Canvas</span></div><input className="canvas-name" value={name} onChange={(e) => setName(e.target.value.slice(0, 100))} aria-label="Canvas name" /><div className="header-actions"><button onClick={fresh}>New</button><button onClick={openLibrary}>Load</button><button className="primary" onClick={save} disabled={saving || !name.trim()}>{saving ? 'Saving…' : currentId ? 'Save changes' : 'Save'}</button><button onClick={exportPng}>Export PNG</button></div></header>
 <div className="workspace"><aside className="toolbar"><span className="section-label">Add element</span><button onClick={() => editor.add(makeElement('rectangle'))}>▭ Rectangle</button><button onClick={() => editor.add(makeElement('circle'))}>○ Circle</button><button onClick={() => editor.add(makeElement('text'))}>T Text</button><hr/><span className="section-label">Edit</span><button onClick={editor.undo} disabled={!editor.canUndo}>↶ Undo</button><button onClick={editor.redo} disabled={!editor.canRedo}>↷ Redo</button><button className="danger" onClick={editor.remove} disabled={!editor.selectedId}>Delete</button><p className="shortcut">Delete: remove<br/>Ctrl/Cmd + Z: undo</p></aside>
 <section className="editor-area"><div className="editor-meta"><span>{dirty ? 'Unsaved changes' : currentId ? 'All changes saved' : 'New canvas'}</span><span>{CANVAS_WIDTH} × {CANVAS_HEIGHT}</span></div><CanvasStage elements={editor.elements} selectedId={editor.selectedId} width={CANVAS_WIDTH} height={CANVAS_HEIGHT} onSelect={editor.setSelectedId} onChange={editor.update} stageRef={stageRef} /></section><PropertiesPanel element={selected} onChange={(patch) => selected && editor.update(selected.id, patch)} /></div>
 {library && <SavedCanvases items={canvases} loading={loading} onLoad={load} onDelete={removeSaved} onClose={() => setLibrary(false)} />}{notice && <div className={`toast ${notice.error ? 'error' : ''}`} role="status">{notice.text}</div>}</main>;
}
